name: Build Appx Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore "Enrolment Register.sln"

      - name: Build project
        run: msbuild "Enrolment Register.sln" /t:Build /p:Configuration=Release

  create-package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Appx package
        run: msbuild "Enrolment Register.csproj" /t:Package /p:Configuration=Release
